name: 'zLoad Balancer (Call)'
run-name: '${{ github.actor }} - Removing Azure Load Balancer'
on:
  workflow_call:
    inputs:
      requestType:
        type: choice
        required: true
        options:
          - destroy
      environment:
        type: string
        required: true
      location:
        type: string
        required: true
      purpose_rg:
        type: string
        required: true
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true
env:
  permissions:
    contents: read
jobs:
  remove-lb:
    name: 'Remove Load Balancer'
    env:
      ARM_CLIENT_ID:        ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET:    ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID:        ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID:  ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ROOT_PATH:            'Azure/Azure-LB'
    runs-on: 
      group: aks-runners
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
    steps:
      - name: 'Checkout - Load Balancer (${{ inputs.purpose_rg }})'
        uses: actions/checkout@v3

      # Terraform Initialize
      - name: 'Terraform Initialize - Load Balancer (${{ inputs.purpose_rg }})'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version:     latest
          tf_actions_subcommand:  'init'
          tf_actions_working_dir: ${{ env.ROOT_PATH }}
          tf_actions_comment:     true
        env:
          TF_VAR_request_type:    '${{ inputs.requestType }}'
          TF_VAR_environment:     '${{ inputs.environment }}'
          TF_VAR_location:        '${{ inputs.location }}'
          TF_VAR_purpose_rg:      '${{ inputs.purpose_rg }}'

      # Terraform Destroy to remove the Load Balancer
      - name: 'Terraform Destroy - Remove Load Balancer'
        if: ${{ inputs.requestType == 'destroy' }}
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version:     latest
          tf_actions_subcommand:  'destroy'
          tf_actions_working_dir: ${{ env.ROOT_PATH }}
          tf_actions_comment:     true
        env:
          TF_VAR_request_type:    '${{ inputs.requestType }}'
          TF_VAR_environment:     '${{ inputs.environment }}'
          TF_VAR_location:        '${{ inputs.location }}'
          TF_VAR_purpose_rg:      '${{ inputs.purpose_rg }}'
