name: 'Deploy MSSQL Server'
run-name: '${{github.actor}} - Deploying to_${{inputs.subscription}}_${{inputs.environment}}'
on:
  workflow_dispatch:
    inputs:
      requestType:
        type: choice
        description: Choose the request type
        options:
          - Create
          - Remove
        required: true
      subscription:
        type: string
        required: true
        description: Please enter your subscription name
      location:
        type: choice
        description: Pick the location
        options:
          - eastus2
          - centralus
      environment:
        type: choice
        description: Choose the environment
        options:
          - dev
          - qa
          - UAT
          - Prod
      purpose:
        type: string
        required: true
        description: Enter purpose for app (3-5 char)
      subnetname:
        type: string
        required: true
        description: Enter the subnet name for DB endpoints
      dbcollation:
        type: string
        required: false
        description: Specify the collation of the database
        default: SQL_Latin1_General_CP1_CI_AS
      skuname:
        type: choice
        description: Select SKU name used by database
        options:
          - S0
          - P2
          - Basic
          - ElasticPool
          - BC_Gen5_2
          - HS_Gen4_1
          - GP_S_Gen5_2
          - DW100c
          - DS100
      zoneredundancy:
        type: choice
        options:
          - "false"
          - "true"

jobs:
  Deploying-Resource-Group:
    if: ${{ inputs.requestType == 'Create' }}
    name: 'Deploying - resource-group'
    uses: ./.github/workflows/CreateResourceGroup.yml
    secrets:
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    with:
      name: 'resource-group'
      subscription: '${{inputs.subscription}}'
      location: '${{inputs.location}}'
      environment: '${{inputs.environment}}'
      purpose: '${{inputs.purpose}}'

  Deploying-Mssql-server:
    if: ${{ inputs.requestType == 'Create' }}
    name: 'Deploying - MSSQL server'
    uses: ./.github/workflows/Createmssqlserver.yml
    needs: Deploying-Resource-Group
    secrets: 
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    with:
      name: 'mssql'
      requestType: '${{inputs.requestType}}'
      subscription: '${{inputs.subscription}}'
      location: '${{inputs.location}}'
      environment: '${{inputs.environment}}'
      purpose: '${{inputs.purpose}}'
      subnetname: '${{inputs.subnetname}}'
      dbcollation: '${{inputs.dbcollation}}'
      skuname: '${{inputs.skuname}}'
      zoneredundancy: '${{inputs.zoneredundancy}}'

  Removing-Mssql-server:
    if: ${{ inputs.requestType == 'Remove' }}
    name: 'Removing - MSSQL server'
    uses: ./.github/workflows/RemoveMssqlserver.yml
    secrets: 
      ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
    with:
      name: 'mssql'
      requestType: '${{inputs.requestType}}'
      subscription: '${{inputs.subscription}}'
      location: '${{inputs.location}}'
      environment: '${{inputs.environment}}'
      purpose: '${{inputs.purpose}}'
