name: 'Windows VM Create or Remove'
on:
  workflow_call:
    inputs:
      requestType:
        type: string
        required: true
      environment:
        type: string
        required: true
      location:
        type: string
        required: true
      vmsize:
        type: string
        required: false
      purpose:
        type: string
        required: true
      purposeRG:
        type: string
        required: true
      projectou:
        type: string
        required: false
      subnetNameWVM:
        type: string
        required: false
      subnetNameWVM2:
        type: string
        required: false
      diskSizeGB:
        type: string
        required: false
      diskStorageAccountType:
        type: string
        required: false
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      ARM_TENANT_ID:
        required: true

jobs:
  wvm-create-or-remove:
    name: 'Create or Remove Windows VM'
    env:
      ARM_CLIENT_ID:        ${{secrets.ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET:    ${{secrets.ARM_CLIENT_SECRET}}
      ARM_TENANT_ID:        ${{secrets.ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID:  ${{secrets.ARM_SUBSCRIPTION_ID}}
      ROOT_PATH:            'Azure/windows-vm'
    runs-on: 
      group: aks-runners
    environment: ${{inputs.environment}}
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Terraform Initialize'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version:     latest
          tf_actions_subcommand:  'init'
          tf_actions_working_dir: ${{env.ROOT_PATH}}
          tf_actions_comment:     true
        env:
          TF_VAR_request_type:              '${{inputs.requestType}}'
          TF_VAR_location:                  '${{inputs.location}}'
          TF_VAR_vm_size:                   '${{inputs.vmsize}}'
          TF_VAR_purpose:                   '${{inputs.purpose}}'
          TF_VAR_purpose_rg:                '${{inputs.purposeRG}}'
          TF_VAR_project_ou:                '${{inputs.projectou}}'
          TF_VAR_subnetname_wvm:            '${{inputs.subnetNameWVM}}'
          TF_VAR_subnetname_wvm2:           '${{inputs.subnetNameWVM2}}'
          TF_VAR_disk_size_gb:              '${{inputs.diskSizeGB}}'
          TF_VAR_disk_storage_account_type: '${{inputs.diskStorageAccountType}}'

      # Plan the creation or removal of the resources
      - name: 'Terraform Plan - Windows VM (${{ inputs.purpose }})'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version:     latest
          tf_actions_subcommand:  'plan'
          tf_actions_working_dir: ${{env.ROOT_PATH}}
          tf_actions_comment:     true
        env:
          TF_VAR_request_type:              '${{inputs.requestType}}'
          TF_VAR_location:                  '${{inputs.location}}'
          TF_VAR_vm_size:                   '${{inputs.vmsize}}'
          TF_VAR_purpose:                   '${{inputs.purpose}}'
          TF_VAR_purpose_rg:                '${{inputs.purposeRG}}'
          TF_VAR_project_ou:                '${{inputs.projectou}}'
          TF_VAR_subnetname_wvm:            '${{inputs.subnetNameWVM}}'
          TF_VAR_subnetname_wvm2:           '${{inputs.subnetNameWVM2}}'
          TF_VAR_disk_size_gb:              '${{inputs.diskSizeGB}}'
          TF_VAR_disk_storage_account_type: '${{inputs.diskStorageAccountType}}'

      # Conditional Apply or Destroy based on requestType
      - name: 'Apply or Destroy - Windows VM (${{ inputs.purpose }})'
        if: ${{ inputs.requestType == 'Create (with New RG)' || inputs.requestType == 'Create (with Existing RG)' }}
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version:     latest
          tf_actions_subcommand:  'apply'
          tf_actions_working_dir: ${{env.ROOT_PATH}}
          tf_actions_comment:     true
        env:
          TF_VAR_request_type:              '${{inputs.requestType}}'
          TF_VAR_location:                  '${{inputs.location}}'
          TF_VAR_vm_size:                   '${{inputs.vmsize}}'
          TF_VAR_purpose:                   '${{inputs.purpose}}'
          TF_VAR_purpose_rg:                '${{inputs.purposeRG}}'
          TF_VAR_project_ou:                '${{inputs.projectou}}'
          TF_VAR_subnetname_wvm:            '${{inputs.subnetNameWVM}}'
          TF_VAR_subnetname_wvm2:           '${{inputs.subnetNameWVM2}}'
          TF_VAR_disk_size_gb:              '${{inputs.diskSizeGB}}'
          TF_VAR_disk_storage_account_type: '${{inputs.diskStorageAccountType}}'

      - name: 'Terraform Destroy - Windows VM (${{ inputs.purpose }})'
        if: ${{ inputs.requestType == 'Remove' }}
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version:     latest
          tf_actions_subcommand:  'destroy'
          tf_actions_working_dir: ${{env.ROOT_PATH}}
          tf_actions_comment:     true
          tf_actions_cli_options: '-auto-approve'
        env:
          TF_VAR_request_type:              '${{inputs.requestType}}'
          TF_VAR_location:                  '${{inputs.location}}'
          TF_VAR_vm_size:                   '${{inputs.vmsize}}'
          TF_VAR_purpose:                   '${{inputs.purpose}}'
          TF_VAR_purpose_rg:                '${{inputs.purposeRG}}'
          TF_VAR_project_ou:                '${{inputs.projectou}}'
          TF_VAR_subnetname_wvm:            '${{inputs.subnetNameWVM}}'
          TF_VAR_subnetname_wvm2:           '${{inputs.subnetNameWVM2}}'
          TF_VAR_disk_size_gb:              '${{inputs.diskSizeGB}}'
          TF_VAR_disk_storage_account_type: '${{inputs.diskStorageAccountType}}'
